--- #YAML:1.0
name:                XML-Compile-Dumper
version:             0.13
abstract:            Remember precompiled XML processors
license:             perl
author:              
    - Mark Overmeer
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Data::Dump::Streamer:          2.08
    Log::Report:                   0.09
    Math::BigInt:                  1.77
    Test::More:                    0.54
    Test::Pod:                     1.00
    XML::Compile:                  0.64
    XML::Compile::Tester:          0.01
    XML::LibXML:                   1.63
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
